id: P58CAC204
initial_creation_type: ocr
source_metadata:
  volumes:
    7546b44184784504b1e6d52c226123d2:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: སྤེལ་མར་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
